# Generated by Django 3.2.9 on 2021-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
