# Generated by Django 3.2.9 on 2021-12-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
