# Generated by Django 3.2.9 on 2021-12-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
