# Generated by Django 3.2.9 on 2021-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211209_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrivals',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
